### ISSUE TITLE
Queries with refetchOnWindowFocus=true are refetched on focus even if not stale

### ISSUE THREAD

**Issue by rutzfutz** [tannerlinsley/react-query#512]
My queries have a non-zero `staleTime` (I'm using 5 minutes, or 5 * 60 * 1000 ms). I just noticed that all my queries get force-refetched by the `onWindowFocus` event handler in `setFocusHandler.js`, even though they are still fresh. This does not match the expected behavior as per the documentation:

> **Stale queries** will automatically be refetched in the background when the browser window is refocused by the user. You can disable this using the refetchOnWindowFocus option in queries or the global config.

It would be great if the code could be adapted to match the documentation. :-)

**Comment by tannerlinsley** [comment]
This should have been fixed. Can you verify that you are using the latest version of RQ?

**Comment by rutzfutz** [comment]
The bug is still there in v1.5.5. Reproduction steps:
1. Set the `staleTime` of any query to a non-zero positive number, e.g. 60 * 1000 for 1 minute.
2. Open the page and wait for the first fetch to succeed.
3. Click away and focus the page again. No refetch will occur (which is okay, as the query is not stale yet).
4. Wait for the `staleTime` set in step 1 to elapse (e.g. 1 minute in my example).
5. Click away and focus the page again. The query will refetch as intended.
6. Now repeat step 5 as often as you like. The query will get refetched every time, even though the query has just been refetched and should NOT be considered stale.

**Comment by rutzfutz** [comment]
Any news on this? Were you able to reproduce the bug with my steps?

**Comment by Avi98** [comment]
@rutzfutz I think it's been resolved in the latest version of react-query. I have just tested with the example provided in [Docs](https://github.com/tannerlinsley/react-query#examples). 

```js 
  const { status, data, error, isFetching } = useQuery("posts", getPosts, { staleTime:10000, });
```
![512](https://user-images.githubusercontent.com/26133749/84378805-630e1200-ac02-11ea-9f34-53c6f1f08803.gif)

**Comment by tannerlinsley** [comment]
I can’t reproduce in the latest version.

**Comment by GuillaumeSpera** [comment]
Hello there,

I would like to point out that there is a regression between from v:^1.5.8 and the version ^2.0.0 about this issue.
I had to rollback to the first one to check.

Your "Basic" example can reproduce this issue with the version 2.0.3.
Just add a staleTime and a log to the useQuery to replicate.
`function Posts({ setPostId }) {
  const { status, data, error, isFetching } = useQuery(
    "posts",
    async () => {
      console.log("QUERY");
      const { data } = await axios.get(
        "https://jsonplaceholder.typicode.com/posts"
      );
      return data;
    },
    { staleTime: 200000 }
  );`

Thanks for the hard work btw !

**Comment by gromin** [comment]
@tannerlinsley  @GuillaumeSpera I can confirm that in 2.0.3 refetchOnWindowFocus happens regardless of whether data is stale or not. Setting `staleTime: Infinity` does nothing.

I like the feature very much, but it would be great if it regarded the `staleTime` option.

**Comment by tannerlinsley** [comment]
Fixed in c3e42c44afa4f19613043e64aca7d88b9d68ba08 🎉
